# Generated by Django 5.0.1 on 2024-04-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_doctor_role_remove_patient_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='cheo',
            field=models.CharField(blank=True, choices=[('Doctor', 'Doctor'), ('Nurse', 'Nurse'), ('Pharmacist', 'Pharmacist'), ('Lab Technician', 'Lab Technician')], max_length=200, null=True),
        ),
    ]
