# Generated by Django 5.0.1 on 2024-04-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_doctor_cheo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='status',
        ),
        migrations.AddField(
            model_name='pregnance',
            name='jina_la_mtoto',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
