# Generated by Django 5.0.1 on 2024-04-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_firsttimepatientinfo_chini_ya_miaka_20_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firsttimepatientinfo',
            name='kajifungua_kwa_kupasuliwa',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
