# Generated by Django 4.1.7 on 2024-04-13 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_firsttimepatientinfo_kajifungua_kwa_kupasuliwa'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('weight', models.CharField(blank=True, max_length=200, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=200, null=True)),
                ('albumin_in_urine', models.CharField(blank=True, max_length=200, null=True)),
                ('blood', models.CharField(blank=True, max_length=200, null=True)),
                ('sugar_in_urine', models.CharField(blank=True, max_length=200, null=True)),
                ('gestational_age_in_weeks', models.CharField(blank=True, max_length=200, null=True)),
                ('fetal_position', models.CharField(blank=True, max_length=200, null=True)),
                ('presentation_from_week_36', models.CharField(blank=True, max_length=200, null=True)),
                ('fetal_heart_rate', models.CharField(blank=True, max_length=200, null=True)),
                ('fetal_movement_after_20_weeks', models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=200, null=True)),
                ('edema_swelling', models.CharField(blank=True, max_length=200, null=True)),
                ('ferrous_sulfate', models.CharField(blank=True, max_length=200, null=True)),
                ('folic_acid', models.CharField(blank=True, max_length=200, null=True)),
                ('mebendazole', models.CharField(blank=True, max_length=200, null=True)),
                ('attending_doctor_signature', models.CharField(blank=True, max_length=200, null=True)),
                ('bp_40_90_or_above', models.BooleanField(null=True)),
                ('hb_below_60_percent', models.BooleanField(null=True)),
                ('albumin_in_urine_positive', models.BooleanField(null=True)),
                ('sugar_in_urine_positive', models.BooleanField(null=True)),
                ('symptoms_of_danger', models.BooleanField(null=True)),
                ('gestational_age_more_than_40_weeks', models.BooleanField(null=True)),
                ('fetal_death_in_uterus', models.BooleanField(null=True)),
                ('swelling_in_legs_or_arms', models.BooleanField(null=True)),
                ('mother_is_having_twins', models.BooleanField(null=True)),
                ('baby_is_too_large_or_too_small_for_its_age', models.BooleanField(null=True)),
                ('mother_has_been_advised_where_to_deliver', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LaboratoryMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(blank=True, max_length=200, null=True)),
                ('other_tests', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pregnancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baby_name', models.CharField(blank=True, max_length=200, null=True)),
                ('pregnancy_number', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreviousPregnancyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregnancy_number', models.IntegerField(default=1)),
                ('number_of_births', models.IntegerField(default=1)),
                ('living_children', models.IntegerField(default=1)),
                ('miscarriages', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pregnancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pregnancy')),
            ],
        ),
        migrations.RemoveField(
            model_name='labaratorymaasurement',
            name='pregnance',
        ),
        migrations.RemoveField(
            model_name='pregnance',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='previouspregnanciesinfo',
            name='pregnance',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='cheo',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='firsttimepatientinfo',
            old_name='kisukari',
            new_name='diabetes',
        ),
        migrations.RenameField(
            model_name='firsttimepatientinfo',
            old_name='kajifungua_kwa_kupasuliwa',
            new_name='gave_birth_through_c_section',
        ),
        migrations.RenameField(
            model_name='firsttimepatientinfo',
            old_name='kuharibika_kwa_mimba_2_au_zaidi',
            new_name='had_miscarriages_2_or_more_times',
        ),
        migrations.RenameField(
            model_name='firsttimepatientinfo',
            old_name='ugonjwa_wa_moyo',
            new_name='heart_disease',
        ),
        migrations.RenameField(
            model_name='firsttimepatientinfo',
            old_name='miaka_10_au_zaid_tokea_mimba_ya_mwisho',
            new_name='more_than_10_years_since_last_pregnancy',
        ),
        migrations.RenameField(
            model_name='firsttimepatientinfo',
            old_name='kifua_kikuu',
            new_name='tuberculosis',
        ),
        migrations.RenameField(
            model_name='firsttimepatientinfo',
            old_name='chini_ya_miaka_20',
            new_name='under_20_years_old',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='anuani',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='umri',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='jina_la_mwenyekiti',
            new_name='chairperson_name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='elimu',
            new_name='education',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='jina_kamili',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='jina_la_mume',
            new_name='husband_name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='kazi',
            new_name='occupation',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='number_ya_simu',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='number_ya_uandikishaji',
            new_name='registration_number',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='kijiji_au_mtaa',
            new_name='village_or_street',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='kata_wilaya',
            new_name='ward_district',
        ),
        migrations.RemoveField(
            model_name='firsttimepatientinfo',
            name='pregnance',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='kimo',
        ),
        migrations.AddField(
            model_name='patient',
            name='height',
            field=models.CharField(choices=[('UP TO 150', 'UP TO 150'), ('BELOW 150', 'BELOW 150')], max_length=110, null=True),
        ),
        migrations.DeleteModel(
            name='AttendenceReport',
        ),
        migrations.DeleteModel(
            name='LabaratoryMaasurement',
        ),
        migrations.DeleteModel(
            name='Pregnance',
        ),
        migrations.DeleteModel(
            name='PreviousPregnanciesInfo',
        ),
        migrations.AddField(
            model_name='pregnancy',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patient'),
        ),
        migrations.AddField(
            model_name='laboratorymeasurement',
            name='pregnancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pregnancy'),
        ),
        migrations.AddField(
            model_name='attendancereport',
            name='attending_doctor_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.doctor'),
        ),
        migrations.AddField(
            model_name='attendancereport',
            name='malaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patient'),
        ),
        migrations.AddField(
            model_name='attendancereport',
            name='pregnancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pregnancy'),
        ),
        migrations.AddField(
            model_name='firsttimepatientinfo',
            name='pregnancy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pregnancy'),
        ),
    ]
