# Generated by Django 5.0.1 on 2024-05-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_doctor_user_alter_patient_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='researcher',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
