# Generated by Django 5.0.1 on 2024-05-05 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_1', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('week_3', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('week_6', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('week_9', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('week_12', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('week_15', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('week_18', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('week_21', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('week_24', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('week_27', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('week_30', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('week_33', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('week_36', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('week_39', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('week_42', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('week_45', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('week_48', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('week_51', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('week_54', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('week_57', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('week_60', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('pregnancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pregnancy')),
            ],
        ),
    ]
