# Generated by Django 5.0.4 on 2024-05-06 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_childweight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='childweight',
            old_name='week_1',
            new_name='month_1',
        ),
        migrations.RenameField(
            model_name='childweight',
            old_name='week_12',
            new_name='month_12',
        ),
        migrations.RenameField(
            model_name='childweight',
            old_name='week_15',
            new_name='month_15',
        ),
        migrations.RenameField(
            model_name='childweight',
            old_name='week_18',
            new_name='month_18',
        ),
        migrations.RenameField(
            model_name='childweight',
            old_name='week_21',
            new_name='month_21',
        ),
        migrations.RenameField(
            model_name='childweight',
            old_name='week_24',
            new_name='month_24',
        ),
        migrations.RenameField(
            model_name='childweight',
            old_name='week_27',
            new_name='month_27',
        ),
        migrations.RenameField(
            model_name='childweight',
            old_name='week_3',
            new_name='month_3',
        ),
        migrations.RenameField(
            model_name='childweight',
            old_name='week_30',
            new_name='month_30',
        ),
        migrations.RenameField(
            model_name='childweight',
            old_name='week_33',
            new_name='month_33',
        ),
        migrations.RenameField(
            model_name='childweight',
            old_name='week_36',
            new_name='month_36',
        ),
        migrations.RenameField(
            model_name='childweight',
            old_name='week_39',
            new_name='month_39',
        ),
        migrations.RenameField(
            model_name='childweight',
            old_name='week_42',
            new_name='month_42',
        ),
        migrations.RenameField(
            model_name='childweight',
            old_name='week_45',
            new_name='month_45',
        ),
        migrations.RenameField(
            model_name='childweight',
            old_name='week_48',
            new_name='month_48',
        ),
        migrations.RenameField(
            model_name='childweight',
            old_name='week_51',
            new_name='month_51',
        ),
        migrations.RenameField(
            model_name='childweight',
            old_name='week_54',
            new_name='month_54',
        ),
        migrations.RenameField(
            model_name='childweight',
            old_name='week_57',
            new_name='month_57',
        ),
        migrations.RenameField(
            model_name='childweight',
            old_name='week_6',
            new_name='month_6',
        ),
        migrations.RenameField(
            model_name='childweight',
            old_name='week_60',
            new_name='month_60',
        ),
        migrations.RenameField(
            model_name='childweight',
            old_name='week_9',
            new_name='month_9',
        ),
    ]
