# Generated by Django 5.0.4 on 2024-05-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rename_week_1_childweight_month_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='previouspregnancyinfo',
            name='Year_of_miscarriage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='previouspregnancyinfo',
            name='expected_date_of_birth',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AddField(
            model_name='previouspregnancyinfo',
            name='start_date_of_the_last_menstration',
            field=models.DateField(default='2024-01-01'),
        ),
    ]
