# Generated by Django 5.0.4 on 2024-05-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_previouspregnancyinfo_year_of_miscarriage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firsttimepatientinfo',
            name='stillbirth_infant_death_week_1',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
