# Generated by Django 5.0.4 on 2024-05-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_firsttimepatientinfo_stillbirth_infant_death_week_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='firsttimepatientinfo',
            name='fifth_pregnancy_or_more',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='firsttimepatientinfo',
            name='first_pregnancy_over_35_years',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='firsttimepatientinfo',
            name='gave_birth_through_c_section_or_vacuum',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='firsttimepatientinfo',
            name='heavy_bleeding_after_child_birth',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='firsttimepatientinfo',
            name='height_less_than_150cm',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='firsttimepatientinfo',
            name='hip_lameness',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='firsttimepatientinfo',
            name='placenta_stuck',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laboratorymeasurement',
            name='rh',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='laboratorymeasurement',
            name='syphilis_sero_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
