# Generated by Django 5.0.4 on 2024-05-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_firsttimepatientinfo_fifth_pregnancy_or_more_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancereport',
            name='attendance_date',
            field=models.DateField(default='2024-01-01'),
        ),
    ]
