# Generated by Django 5.0.4 on 2024-05-06 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_attendancereport_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancereport',
            name='malaria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.patient'),
        ),
    ]
