# Generated by Django 5.0.4 on 2024-05-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_attendancereport_malaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregnancy',
            name='birth_place',
            field=models.CharField(blank=True, choices=[('Hospital', 'Hospital'), ('Home', 'Home'), ('Others', 'Others')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pregnancy',
            name='birth_weight',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pregnancy',
            name='child_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pregnancy',
            name='date_of_birth',
            field=models.DateTimeField(default='2024-01-01'),
        ),
        migrations.AddField(
            model_name='pregnancy',
            name='father_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pregnancy',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='MALE', max_length=10),
        ),
        migrations.AddField(
            model_name='pregnancy',
            name='residence',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
