# Generated by Django 5.0.4 on 2024-05-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_childfirstattendence_pregnancy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/assets/images'),
        ),
    ]
