# Generated by Django 5.0.4 on 2024-05-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_patient_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='position',
            field=models.CharField(blank=True, choices=[('Doctor', 'Doctor'), ('Nurse', 'Nurse'), ('Pharmacist', 'Pharmacist'), ('Medical Lab', 'Medical Lab')], max_length=200, null=True),
        ),
    ]
