# Generated by Django 5.0.4 on 2024-05-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_doctor_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregnancy',
            name='birth_weight',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='child_number',
            field=models.CharField(max_length=15),
        ),
    ]
