# Generated by Django 5.0.1 on 2024-05-14 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_pregnancy_birth_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='password',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patient_registration_number',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.patient'),
        ),
    ]
