# Generated by Django 5.0.1 on 2024-05-14 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_remove_appointment_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='user',
            new_name='patient',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='address',
        ),
    ]
