# Generated by Django 5.0.6 on 2024-07-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0028_rename_month_1_childweight_month_0"),
    ]

    operations = [
        migrations.RenameField(
            model_name="childweight",
            old_name="month_27",
            new_name="month_1",
        ),
        migrations.RenameField(
            model_name="childweight",
            old_name="month_33",
            new_name="month_10",
        ),
        migrations.RenameField(
            model_name="childweight",
            old_name="month_39",
            new_name="month_11",
        ),
        migrations.RenameField(
            model_name="childweight",
            old_name="month_45",
            new_name="month_13",
        ),
        migrations.RenameField(
            model_name="childweight",
            old_name="month_51",
            new_name="month_14",
        ),
        migrations.RenameField(
            model_name="childweight",
            old_name="month_57",
            new_name="month_16",
        ),
        migrations.AddField(
            model_name="childweight",
            name="month_17",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="childweight",
            name="month_19",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="childweight",
            name="month_2",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="childweight",
            name="month_20",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="childweight",
            name="month_22",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="childweight",
            name="month_23",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="childweight",
            name="month_4",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="childweight",
            name="month_5",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="childweight",
            name="month_7",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="childweight",
            name="month_8",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
